# Generated by Django 5.0.4 on 2024-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='nom',
        ),
        migrations.AddField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('alum', 'Alumne'), ('prof', 'Professor')], default='alum', max_length=100),
        ),
    ]
